활동 그룹 관리 및 과제 제출 조회 및 피드백 생성
KGU-C-Lab/clab-platforms pull request #201
Opened 2024-08-14 15:33 UTC by Jeong-Ag

## Summary

>#39

활동 그룹 관리를 위한 컴포넌트를 생성하고 과제 조회와 피드백 기능을 구현합니다.

## Tasks

- 활동 그룹 공지사항, 주차별 활동, 과제 관리 기능
- 과제 제출 조회 및 미제출 명단 조회
- 과제 피드백 기능

## ETC

- 부모 게시판 하위의 게시판 리스트를 나타내는 경우 하위 게시판이 수정되거나 추가되어도 리스트에 즉시 반영되지 않고 새로고침 해야 변경된 내용이 반영됩니다 (ex 관리 페이지 내에서 주차별 활동에 과제를 생성한 경우 바로 조회되지 않고 새로고침 해야 나타남).
- query key를 DETAIL, BOARD 등으로 나누어 사용하는 부분이 원인으로 예상됩니다. 해당 부분 관련하여 고민한 후 리팩토링 하겠습니다.
- 활동 그룹 정보 관리 기능은 백엔드 api 수정 완료되면 연동하겠습니다.

## Screenshot

<img width="1792" alt="스크린샷 2024-08-14 오후 10 04 47" src="https://github.com/user-attachments/assets/5e0638ab-0efb-4d8f-a294-dc1979de021b">
<img width="1792" alt="스크린샷 2024-08-14 오후 10 30 18" src="https://github.com/user-attachments/assets/2c86f562-81ff-4012-bdfa-4b674d922b78">
<img width="1792" alt="스크린샷 2024-08-14 오후 6 48 14" src="https://github.com/user-attachments/assets/31872f72-54fd-4f58-a1d1-ccd80706c2cf">
<img width="1792" alt="스크린샷 2024-08-14 오후 6 48 22" src="https://github.com/user-attachments/assets/15947495-1d2f-4743-a2ab-50b95b61b61a">
<img width="1792" alt="스크린샷 2024-08-14 오후 6 43 15" src="https://github.com/user-attachments/assets/7c72e996-c1e2-4ab5-984b-19d8e63b8c53">
<img width="1792" alt="스크린샷 2024-08-14 오후 6 43 18" src="https://github.com/user-attachments/assets/7492c82b-a36e-4815-92bc-d21303062634">
<img width="1792" alt="스크린샷 2024-08-14 오후 6 43 07" src="https://github.com/user-attachments/assets/d9bfc6a5-a538-4a63-8297-0224c8ce71f2">

2024-08-15 07:36 UTC, gwansikk requested changes

2024-08-15 07:36 UTC, gwansikk commented on apps/member/src/components/group/ActivityAssignmentEditor/ActivityAssignmentEditor.tsx
> +                첨부 파일
첨부파일 디자인 컴포넌트가 있으면 활용하기 좋을 거 같아요, 후에 DS 컴포넌트에 추가 부탁드려요 @SWARVY

2024-08-15 07:36 UTC, gwansikk commented on apps/member/src/components/group/AssignmentFeedbackModal/AssignmentFeedbackModal.tsx
> +    if (post.children?.[0])
```suggestion
    if (post.children?.[0]) {
```

2024-08-15 07:36 UTC, gwansikk commented on apps/member/src/components/group/AssignmentFeedbackModal/AssignmentFeedbackModal.tsx
> +    else
```suggestion
    else {
```

2024-08-15 07:36 UTC, gwansikk commented on apps/member/src/hooks/queries/activity/useActivityGroupBoardByCategory.ts
> +export function useActivityGroupBoardByCategory(
Params가 3개 이상이 될 경우 Options Object Pattern으로 하면 유지보수에 좋아요

```ts
useActivityGroupBoardByCategory({
  activityGroupId: 123,
  category: 'someCategory',
  page: 1,
  size: 10,
});
```

1. 파라미터의 순서에 상관없이 명시적으로 값을 전달할 수 있다.
2. 새로운 파라미터가 추가되어도 기존 코드에 큰 영향을 주지 않는다.
3. 기본 값을 설정하기 쉽다.

2024-08-15 07:36 UTC, gwansikk commented on apps/member/src/hooks/queries/activity/useActivityGroupBoardByParent.ts
> +export function useActivityGroupBoardByParent(
해당 훅도 Options Object Pattern으로 개선하면 유지보수하기 용이해져요

2024-08-15 07:36 UTC, gwansikk commented on apps/member/src/hooks/queries/activity/useActivityGroupMemberList.ts
> +export function useActivityGroupMemberList(
해당 훅도 Options Object Pattern으로 개선하면 유지보수하기 용이해져요

2024-08-15 08:15 UTC, SWARVY requested changes
수고 많으셨습니다잇

2024-08-15 08:15 UTC, SWARVY commented on apps/member/src/components/group/ActivityPostEditor/ActivityPostEditor.tsx
> +  };
단순 return 구문만 존재하는거라면 아래와 같이 작성하는게 더 깔끔할 것 같네요

```suggestion
  const handleEditWeeklyClick = (prevData: ActivityBoardType) => openModal({
      title: '수정하기',
      custom: <ActivityBoardEditModal groupId={groupId} prevData={prevData} />,
    });
 
```

2024-08-15 08:15 UTC, SWARVY commented on apps/member/src/components/group/GroupCreateSection/GroupCreateSection.tsx
> +    category: CategoryOptions[0].value,
저번 피드백을 반영하셨네요 좋습니다!

2024-08-15 08:15 UTC, SWARVY commented on apps/member/src/pages/GroupAssignmentPage/GroupAssignmentPage.tsx
> +    (member) => member.role === 'LEADER' && member.memberId === myProfile?.id,
해당 부분도`'LEADER'`를 하드코딩하기보단, 상수로 관리하여 휴먼에러를 방지해봅시다

2024-08-15 10:14 UTC, SWARVY commented on apps/member/src/hooks/queries/activity/useActivityGroupBoardByCategory.ts
> +export function useActivityGroupBoardByCategory(
https://www.youtube.com/shorts/xirRddcqbrU

Options Object Pattern이라고도 하지만, `RORO(Receive Object, Return Object)` 라고도 합니다.
해당 영상에 잘 설명되어있으니 한번 보시는거 추천드립니당

2024-08-15 10:58 UTC, Jeong-Ag commented on apps/member/src/hooks/queries/activity/useActivityGroupBoardByCategory.ts
> +export function useActivityGroupBoardByCategory(
`WithPaginationParams`와 함께 사용해서 관련 내용 반영하도록 하겠습니다!

2024-08-15 11:07 UTC, Jeong-Ag commented on apps/member/src/components/group/ActivityConfigTableSection/ActivityConfigTableSection.tsx
> +interface Props {
정의하여 사용하는 Props가 하나만 존재하는 경우엔 단순히 Props로 사용하곤 했는데 구체화 하는 게 나중을 생각하면 더 좋을 것 같네요 ~Props로 변경하도록 하겠습니다!

2024-08-15 11:11 UTC, Jeong-Ag commented on apps/member/src/components/group/ActivityPostEditor/ActivityPostEditor.tsx
> +    new Array(data.length).fill(false),
확인 후 변경하겠습니다!!

2024-08-15 12:50 UTC, gwansikk requested changes

2024-08-15 12:50 UTC, gwansikk commented on apps/member/src/hooks/queries/activity/useActivityGroupBoardByParent.ts
> +    queryKey: [...ACTIVITY_QUERY_KEY.BOARDS(), 'by-parent', parentId],
해당 프로젝트에서는 QueryKey를 Query Key Factory를 사용하고 있어요 , 현재 해당 코드에서는 `by-parent`와 `parentId`를 선언하여 사용하면, 이후 쿼리키를 관리하기 어려워져요. 해당 `ACTIVITY_QUERY_KEY`에 해당 QueryKey를 선언적으로 사용할 수 있도록 개선해보는건 어떨까요


ref:
- https://tkdodo.eu/blog/leveraging-the-query-function-context#query-key-factories

2024-08-15 13:03 UTC, Jeong-Ag commented on apps/member/src/hooks/queries/activity/useActivityGroupBoardByParent.ts
> +    queryKey: [...ACTIVITY_QUERY_KEY.BOARDS(), 'by-parent', parentId],
감사합니다 남겨주신 글 참고해서 읽어보고 추가적으로 선언하여 개선하겠습니다~

2024-08-17 10:46 UTC, Jeong-Ag commented on apps/member/src/hooks/queries/activity/useActivityGroupBoardByParent.ts
> +    queryKey: [...ACTIVITY_QUERY_KEY.BOARDS(), 'by-parent', parentId],
현재 별도로 분리하지 않고 BOARD의 params로 설정하였는데 따로 BOARD_CATEGORY나 BOARD_PARENT로 별도 선언하는 방법과 비교하면 어떤 것이 더 관리하기 좋은 방법일지 여쭤보고 싶습니다. 쿼리 키가 많아질 것을 걱정하여 위와 같은 방법으로 사용했는데 별도 선언하는 것이 더 직관적이고 관리하기 쉬울까요?

2024-08-17 11:42 UTC, SWARVY requested changes
고민한 흔적이 많이 보이네요! 리뷰 내용 확인하시고 필요한 부분은 수정해주세요 :)

2024-08-17 11:42 UTC, SWARVY commented on apps/member/src/components/group/ActivityAssignmentEditor/ActivityAssignmentEditor.tsx
> +        category: 'ASSIGNMENT',
여기도 가능하면 상수로 따로 관리해주세요

2024-08-17 11:42 UTC, SWARVY commented on apps/member/src/components/group/ActivityBoardEditModal/ActivityBoardEditModal.tsx
> +        {prevData.category !== 'FEEDBACK' && (
위에도 리뷰를 남겼는데, 해당 부분들을 다 상수처리해서 관리하시면 될 듯 합니다.

2024-08-17 11:42 UTC, SWARVY commented on apps/member/src/hooks/queries/activity/useActivityGroupBoard.ts
> +    queryKey: ACTIVITY_QUERY_KEY.BOARD({ id: id }),
키가 같으면 생략해도 됩니다.

```suggestion
    queryKey: ACTIVITY_QUERY_KEY.BOARD({ id }),
```

2024-08-17 11:42 UTC, SWARVY commented on apps/member/src/pages/GroupAssignmentPage/GroupAssignmentPage.tsx
> +  const isLeader = groupDetail?.groupMembers.some(
배열 내장함수를 적극적으로 사용하는거 보기 좋습니다!

2024-08-17 11:42 UTC, SWARVY commented on apps/member/src/api/activity.ts
>  }
해당 로직의 전문을 보았을 때, data fetching으로 받아온 결과인 `data`를 `groupBoardParser`에서 `notice`, `activities`, `assignments`를 추가하여 반환하고 있어요.

리액트(넥스트도 마찬가지입니다)에서 가장 중요한건 불변성 유지입니다. 리액트에서는 직접 데이터를 수정하기보단 해당 데이터를 기반으로 생성된 복사본을 생성해서 원본 데이터를 유지하면서도 새로운 데이터를 만들어내는 방식을 권장하고 있어요.

따라서 `data`를 직접적으로 수정하기보단, 해당 데이터를 바탕으로 새로운 객체를 만들고 반환하시는 것을 추천드립니다.

```ts
return {
  ...data.data,
  notices,
  activities,
  assignments,
}
```

https://f-lab.kr/insight/react-immutability-importance

위의 글도 한번 읽어보시는걸 추천드려요

2024-08-17 12:07 UTC, Jeong-Ag commented on apps/member/src/components/group/ActivityAssignmentEditor/ActivityAssignmentEditor.tsx
> +        category: 'ASSIGNMENT',
[31b225c](https://github.com/KGU-C-Lab/clab-platforms/pull/201/commits/31b225c5fbec73af5261c5751722a403a8ef110d) 해당 부분을 놓쳤네요! 상수 분리 하였습니다~

2024-08-17 12:08 UTC, Jeong-Ag commented on apps/member/src/api/activity.ts
>  }
[a7a374f](https://github.com/KGU-C-Lab/clab-platforms/pull/201/commits/a7a374f990f79768ec0b63d41611a90bddc988b1) 생각하지 못한 부분이네요. 도움이 될 것 같아요 감사합니다 :)

2024-08-17 12:18 UTC, gwansikk commented on apps/member/src/hooks/queries/activity/useActivityGroupBoardByParent.ts
> +    queryKey: [...ACTIVITY_QUERY_KEY.BOARDS(), 'by-parent', parentId],
제 생각으로는 별도로 분리하는게 관리성이 좋다 입니다, 쿼리키는 다른 파일에서도 사용할 수 있는데요(쿼리키를 비활성화) 따로 분리하여 관리할 경우 직관적이고 명시적으로 사용할 수 있다고 생각해요

2024-08-17 12:19 UTC, gwansikk approved these changes

2024-08-17 12:38 UTC, SWARVY approved these changes

2024-08-17 12:42 UTC, merged