feat(member): 멤버 권환 관리 기능 추가
KGU-C-Lab/clab-platforms pull request #219
Opened 2024-08-22 11:27 UTC by Jeong-Ag

## Summary

#216

동아리 멤버의 권한을 관리하는 기능을 추가합니다. 관리 페이지 내에서 특정 인원의 권한을 조정할 수 있습니다.

## Tasks

- 멤버 권한 상수화
- 멤버 권한 변경 기능
- 권한 별 멤버 조회
- 이름, id 통한 멤버 검색
- 한 페이지 내에 여러 개의 `pagination`이 존재하는 경우, 한 `pagination`의 page 이동 시 다른 section의 page 또한 움직여지는 문제 해결

## Screenshot

<img width="1552" alt="스크린샷 2024-08-22 오후 6 24 49" src="https://github.com/user-attachments/assets/fa1f8d13-4b55-4e32-8a41-aff4f591d56b">
<img width="1552" alt="스크린샷 2024-08-22 오후 6 25 04" src="https://github.com/user-attachments/assets/c9b654a9-40d4-437f-9e72-edaeed6d3a25">
<img width="1552" alt="스크린샷 2024-08-22 오후 6 25 12" src="https://github.com/user-attachments/assets/22d608cc-a6cf-4d8a-b4a6-3ed9024271d4">

2024-08-22 11:50 UTC, gwansikk requested changes

2024-08-22 11:50 UTC, gwansikk commented on apps/member/src/components/manage/ManageLevelSection/ManageLevelSection.tsx
> +import { RoleLevelKey } from '@type/member';
```suggestion
import type { RoleLevelKey } from '@type/member';
```

2024-08-22 11:50 UTC, gwansikk commented on apps/member/src/constants/state.ts
> +  GUEST: 0,
게스트는 특수한 권한이므로 빼도 될 거 같아요

2024-08-22 11:50 UTC, gwansikk commented on apps/member/src/hooks/common/usePagination.ts
> +      navigate(`?${sectionName}=` + page);
파라미터를 만드는 것을 함슈로 추상화하면 관리하기 용이할 거 같아요

2024-08-22 11:50 UTC, gwansikk commented on apps/member/src/hooks/queries/member/useMemberRole.ts
> +import { RoleLevelKey } from '@type/member';
```suggestion
import type { RoleLevelKey } from '@type/member';
```

2024-08-22 11:50 UTC, gwansikk commented on apps/member/src/hooks/queries/member/useMemberRoleMutation.ts
> +          message: '레벨이 수정되었어요.',
사용자 입장에서는 레벨보단 권한이라고 명명하는게 좋을 거 같아요 @Jeong-Ag @SWARVY 다른 분들 생각 공유 부탁드려요

2024-08-22 11:54 UTC, Jeong-Ag commented on apps/member/src/hooks/queries/member/useMemberRoleMutation.ts
> +          message: '레벨이 수정되었어요.',
그렇다면 "사용자 권한이 변경되었어요"라는 메세지로 바꾸는 건 어떨까요?

2024-08-22 12:03 UTC, gwansikk commented on apps/member/src/hooks/queries/member/useMemberRoleMutation.ts
> +          message: '레벨이 수정되었어요.',
> 그렇다면 "사용자 권한이 변경되었어요"라는 메세지로 바꾸는 건 어떨까요?

좋아요 👍👍

2024-08-23 01:10 UTC, SWARVY approved these changes
개인사정으로 리뷰가 하루 늦었네요 ㅠㅠ

저번에 의견 공유했던 내용들이 거의 다 반영되어있어서 크게 리뷰드릴 건 없는 것 같습니다!
수고 많으셨어요.

2024-08-23 01:10 UTC, SWARVY commented on apps/member/src/components/manage/ManageLevelSection/ManageLevelSection.tsx
> +  }, [mode]);
`navigation`이 dependency에서 빠져있다고하니까 이 부분 추가해주세욥

2024-08-23 01:29 UTC, Jeong-Ag commented on apps/member/src/hooks/common/usePagination.ts
> +      navigate(`?${sectionName}=` + page);
[2e5fa32](https://github.com/KGU-C-Lab/clab-platforms/pull/219/commits/2e5fa32cc0cd2408cc89b5de61ee3e9bb11531b2) `createQueryParams` 함수 생성하여 리팩토링 했습니다!

2024-08-23 01:36 UTC, gwansikk approved these changes
LGTM

2024-08-23 01:43 UTC, merged